/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.aibank.api.controller;

import com.aibank.api.model.Account;
import com.aibank.api.model.Balances;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import jakarta.validation.constraints.*;
import java.util.List;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-03-30T16:19:24.480113+08:00[Asia/Hong_Kong]", comments = "Generator version: 7.12.0")
@Validated
public interface AccountsApi {

    @RequestMapping(
        method = RequestMethod.GET,
        value = "/accounts",
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    
    ResponseEntity<List<Account>>getAccounts(
        @NotNull  @RequestHeader(value = "customerId", required = true) String customerId
    );

    @RequestMapping(
        method = RequestMethod.GET,
        value = "/accounts/{accountId}",
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    ResponseEntity<Account> getAccountsByAccountId(
        @NotNull  @RequestHeader(value = "customerId", required = true) String customerId,
        @Size(min = 1, max = 40)  @PathVariable("accountId") String accountId
    );

    @RequestMapping(
        method = RequestMethod.GET,
        value = "/accounts/{accountId}/balances",
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    ResponseEntity<Balances> getBalances(
        @NotNull  @RequestHeader(value = "customerId", required = true) String customerId,
        @Size(min = 1, max = 40)  @PathVariable("accountId") String accountId
    );

}
